### PR TITLE
Add support for rspec 3.7.0

### PR DESCRIPTION
**Pull request by dthorsen**

### CODE REVIEW

**Comment by dthorsen** [comment]
@michaelglass This is breaking some builds for us right now. Any chance this could get reviewed/merged today?

**Comment by zendesk-thittesdorf** [comment]
We could really use this merge as well.

**Comment by oehlschl** [comment]
Same!

**Comment by dthorsen** [comment]
@michaelglass The workarounds we have to put in place to get this working are pretty ugly (due to dependencies we don't control). In the short term can we get this merged quickly to get our pipelines working?

In the long term I would like to get the upper constraint removed from the gem so that this doesn't break every time a new version of the rspec gem is released.

**Comment by avit** [comment]
@dthorsen I took a shot at this too before seeing your pull request (#86), I also unblocked the other gem version constraints across the test matrix so it should "just work" with other rspec 3 versions.

Hoping we can get a review and merge on one of these soon too. 👍

**Comment by Empact** [comment]
@michaelglass could we get this released? It's holding up updates...

**Comment by omnibs** [comment]
Sorry everyone, @michaelglass is on sabbatical. Me and @SamGerber reviewed this and are giving it a 👍. We're not super familiar with the project but we don't wanna leave folks hanging.

Thanks everyone for contributing the update!

**Pull request merged**
